# Generated by Django 3.0.4 on 2020-05-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default='By Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
