# Generated by Django 3.0.4 on 2020-05-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='upload_by',
            field=models.CharField(default=' Admin', max_length=100),
        ),
    ]
