# Generated by Django 3.0.4 on 2020-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200501_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DefenceBlog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chead2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HolyPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Monuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareBlog',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=500)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chead2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('upload_by', models.CharField(default=' Admin', max_length=100)),
                ('title', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
